defmodule Yelixer.MultiCommitFixtureTest do
  @moduledoc """
  Static multi-commit fixture tests (CX-2cq).

  Each fixture in multi_commit_fixtures.json is a sequence of
  hex-encoded yjs updates representing successive commits to the same
  doc, generated by multi_commit_generator.mjs. This test loads the
  updates in order, applies each one to a fresh yelixer Doc, and
  verifies the final content matches the expected value produced by
  Node yjs.

  The point of these (vs the differential tests in diff_yjs_test.exs)
  is static regression coverage without a Node runtime dependency —
  these run in plain CI against committed binary data.
  """
  use ExUnit.Case, async: true

  alias Yelixer.{Doc, Encoding}
  alias Yelixer.Types.{Text, YMap, Array}

  @fixtures_path Path.expand("../fixtures/multi_commit_fixtures.json", __DIR__)

  setup_all do
    case File.read(@fixtures_path) do
      {:ok, json} ->
        fixtures = Jason.decode!(json)
        {:ok, fixtures: fixtures}

      {:error, :enoent} ->
        flunk("""
        Missing multi_commit_fixtures.json — regenerate with:
          node apps/yelixer/test/fixtures/multi_commit_generator.mjs
        """)
    end
  end

  defp fixture(fixtures, name), do: Enum.find(fixtures, &(&1["name"] == name))

  defp load_chain(fixture) do
    Enum.reduce(fixture["update_hexes"], Doc.new(), fn hex, doc ->
      bytes = Base.decode16!(hex, case: :lower)
      {:ok, doc} = Encoding.apply_update(doc, bytes)
      doc
    end)
  end

  # Re-encode the doc and decode into a fresh one. This exercises
  # yelixer's encode path on a doc produced by decoding yjs binaries,
  # which is the CX-2sv pattern. Without this round-trip, the fixture
  # tests only exercise decode correctness, not encode correctness.
  defp reencode_roundtrip(%Doc{} = doc) do
    bin = Encoding.encode_update(doc)
    {:ok, fresh} = Encoding.apply_update(Doc.new(), bin)
    fresh
  end

  # ---------------------------------------------------------------------------
  # Text fixtures
  # ---------------------------------------------------------------------------

  test "text_simple_chain: 3 insert commits", %{fixtures: fs} do
    f = fixture(fs, "text_simple_chain")
    doc = load_chain(f)
    assert Text.to_string(doc, "content") == f["expected_text"]
    # Re-encode roundtrip to exercise yelixer's encode path.
    assert Text.to_string(reencode_roundtrip(doc), "content") == f["expected_text"]
  end

  test "text_delete_from_start_chain: exercises Item.split left half", %{fixtures: fs} do
    f = fixture(fs, "text_delete_from_start_chain")
    doc = load_chain(f)
    assert Text.to_string(doc, "content") == f["expected_text"]
    assert Text.to_string(reencode_roundtrip(doc), "content") == f["expected_text"]
  end

  test "text_replace_all_chain: MCP write pattern across 3 commits", %{fixtures: fs} do
    f = fixture(fs, "text_replace_all_chain")
    doc = load_chain(f)
    assert Text.to_string(doc, "content") == f["expected_text"]
    assert Text.to_string(reencode_roundtrip(doc), "content") == f["expected_text"]
  end

  test "text_envelope_chain: 5-commit envelope (CX-2sv pattern)", %{fixtures: fs} do
    f = fixture(fs, "text_envelope_chain")
    doc = load_chain(f)
    assert Text.to_string(doc, "content") == f["expected_text"]
    assert YMap.to_map(doc, "root") == f["expected_map"]

    reloaded = reencode_roundtrip(doc)
    assert Text.to_string(reloaded, "content") == f["expected_text"]
    assert YMap.to_map(reloaded, "root") == f["expected_map"]
  end

  test "text_long_chain: 21 successive appends", %{fixtures: fs} do
    f = fixture(fs, "text_long_chain")
    doc = load_chain(f)
    assert Text.to_string(doc, "content") == f["expected_text"]
    assert Text.to_string(reencode_roundtrip(doc), "content") == f["expected_text"]
  end

  test "text_interleaved_edits_chain: mid-doc edits across 4 commits", %{fixtures: fs} do
    f = fixture(fs, "text_interleaved_edits_chain")
    doc = load_chain(f)
    assert Text.to_string(doc, "content") == f["expected_text"]
    assert Text.to_string(reencode_roundtrip(doc), "content") == f["expected_text"]
  end

  # ---------------------------------------------------------------------------
  # Map fixture
  # ---------------------------------------------------------------------------

  test "map_chain: set, overwrite, delete", %{fixtures: fs} do
    f = fixture(fs, "map_chain")
    doc = load_chain(f)
    assert YMap.to_map(doc, "root") == f["expected_map"]
    assert YMap.to_map(reencode_roundtrip(doc), "root") == f["expected_map"]
  end

  # ---------------------------------------------------------------------------
  # Array fixture
  # ---------------------------------------------------------------------------

  test "array_chain: push, insert middle, delete first", %{fixtures: fs} do
    f = fixture(fs, "array_chain")
    doc = load_chain(f)
    assert Array.to_list(doc, "items") == f["expected_array"]
    assert Array.to_list(reencode_roundtrip(doc), "items") == f["expected_array"]
  end
end
